# Generated by Django 5.1.4 on 2025-02-11 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_panel', '0002_remove_productimage_image_productimage_image_url'),
        ('user_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fulfillx_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inventory', models.IntegerField(default=0)),
                ('shopify_product_id', models.CharField(blank=True, max_length=255, null=True)),
                ('pushed_to_shopify', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_panel.products', unique=True)),
            ],
        ),
    ]
