# Generated by Django 5.1.4 on 2025-02-11 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_panel', '0002_remove_productimage_image_productimage_image_url'),
        ('user_panel', '0003_remove_myproducts_id_alter_myproducts_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproducts',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='staff_panel.products'),
        ),
    ]
