# Generated by Django 5.1.4 on 2025-02-18 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0005_myproducts_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyorder',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='user_panel.shop'),
        ),
        migrations.AddField(
            model_name='shopifyorderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_panel.myproducts'),
        ),
    ]
